// Code generated by go generate; DO NOT EDIT.
//go:generate go run ./gen -input client.go -output logging_client_gen.go -template gen/templates/logging2.tmpl

package api

import (
	"context"
	"time"

	"github.com/cristianoliveira/figma-cli/internal/logging"
)

// GetFile implements Client.GetFile with logging.
func (lc *LoggingClient) GetFile(ctx context.Context, fileKey string, opts ...GetFileOption) (*File, error) {
	start := time.Now()
	// TODO: extract options and log fields
	lc.logger.Debug(ctx, "GetFile request", logging.String("fileKey", fileKey), logging.Any("opts", opts))

	result, err := lc.client.GetFile(ctx, fileKey, opts...)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("fileKey", fileKey))

	fields = append(fields, logging.Any("opts", opts))

	if err != nil {
		lc.logger.Error(ctx, "GetFile failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetFile success", fields...)
	}
	return result, err
}

// GetNode implements Client.GetNode with logging.
func (lc *LoggingClient) GetNode(ctx context.Context, fileKey string, nodeID string, opts ...GetNodeOption) (*Node, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "GetNode request", logging.String("fileKey", fileKey), logging.String("nodeID", nodeID), logging.Any("opts", opts))

	result, err := lc.client.GetNode(ctx, fileKey, nodeID, opts...)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("fileKey", fileKey))

	fields = append(fields, logging.String("nodeID", nodeID))

	fields = append(fields, logging.Any("opts", opts))

	if err != nil {
		lc.logger.Error(ctx, "GetNode failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetNode success", fields...)
	}
	return result, err
}

// GetFileNodes implements Client.GetFileNodes with logging.
func (lc *LoggingClient) GetFileNodes(ctx context.Context, fileKey string, nodeIDs []string, opts ...GetFileNodesOption) (*FileNodesResponse, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "GetFileNodes request", logging.String("fileKey", fileKey), logging.Any("nodeIDs", nodeIDs), logging.Any("opts", opts))

	result, err := lc.client.GetFileNodes(ctx, fileKey, nodeIDs, opts...)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("fileKey", fileKey))

	fields = append(fields, logging.Any("nodeIDs", nodeIDs))

	fields = append(fields, logging.Any("opts", opts))

	if err != nil {
		lc.logger.Error(ctx, "GetFileNodes failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetFileNodes success", fields...)
	}
	return result, err
}

// GetImage implements Client.GetImage with logging.
func (lc *LoggingClient) GetImage(ctx context.Context, fileKey string, nodeIDs []string, options *ImageOptions) (map[string]string, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "GetImage request", logging.String("fileKey", fileKey), logging.Any("nodeIDs", nodeIDs), logging.Any("options", options))

	result, err := lc.client.GetImage(ctx, fileKey, nodeIDs, options)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("fileKey", fileKey))

	fields = append(fields, logging.Any("nodeIDs", nodeIDs))

	fields = append(fields, logging.Any("options", options))

	if err != nil {
		lc.logger.Error(ctx, "GetImage failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetImage success", fields...)
	}
	return result, err
}

// GetComments implements Client.GetComments with logging.
func (lc *LoggingClient) GetComments(ctx context.Context, fileKey string) ([]*Comment, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "GetComments request", logging.String("fileKey", fileKey))

	result, err := lc.client.GetComments(ctx, fileKey)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("fileKey", fileKey))

	if err != nil {
		lc.logger.Error(ctx, "GetComments failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetComments success", fields...)
	}
	return result, err
}

// PostComment implements Client.PostComment with logging.
func (lc *LoggingClient) PostComment(ctx context.Context, fileKey string, comment *CommentRequest) (*Comment, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "PostComment request", logging.String("fileKey", fileKey), logging.Any("comment", comment))

	result, err := lc.client.PostComment(ctx, fileKey, comment)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("fileKey", fileKey))

	fields = append(fields, logging.Any("comment", comment))

	if err != nil {
		lc.logger.Error(ctx, "PostComment failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "PostComment success", fields...)
	}
	return result, err
}

// DeleteComment implements Client.DeleteComment with logging.
func (lc *LoggingClient) DeleteComment(ctx context.Context, fileKey string, commentID string) error {
	start := time.Now()
	lc.logger.Debug(ctx, "DeleteComment request", logging.String("fileKey", fileKey), logging.String("commentID", commentID))

	err := lc.client.DeleteComment(ctx, fileKey, commentID)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("fileKey", fileKey))

	fields = append(fields, logging.String("commentID", commentID))

	if err != nil {
		lc.logger.Error(ctx, "DeleteComment failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "DeleteComment success", fields...)
	}
	return err
}

// GetCommentReactions implements Client.GetCommentReactions with logging.
func (lc *LoggingClient) GetCommentReactions(ctx context.Context, fileKey string, commentID string) ([]*Reaction, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "GetCommentReactions request", logging.String("fileKey", fileKey), logging.String("commentID", commentID))

	result, err := lc.client.GetCommentReactions(ctx, fileKey, commentID)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("fileKey", fileKey))

	fields = append(fields, logging.String("commentID", commentID))

	if err != nil {
		lc.logger.Error(ctx, "GetCommentReactions failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetCommentReactions success", fields...)
	}
	return result, err
}

// PostCommentReaction implements Client.PostCommentReaction with logging.
func (lc *LoggingClient) PostCommentReaction(ctx context.Context, fileKey string, commentID string, emoji string) error {
	start := time.Now()
	lc.logger.Debug(ctx, "PostCommentReaction request", logging.String("fileKey", fileKey), logging.String("commentID", commentID), logging.String("emoji", emoji))

	err := lc.client.PostCommentReaction(ctx, fileKey, commentID, emoji)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("fileKey", fileKey))

	fields = append(fields, logging.String("commentID", commentID))

	fields = append(fields, logging.String("emoji", emoji))

	if err != nil {
		lc.logger.Error(ctx, "PostCommentReaction failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "PostCommentReaction success", fields...)
	}
	return err
}

// DeleteCommentReaction implements Client.DeleteCommentReaction with logging.
func (lc *LoggingClient) DeleteCommentReaction(ctx context.Context, fileKey string, commentID string, emoji string) error {
	start := time.Now()
	lc.logger.Debug(ctx, "DeleteCommentReaction request", logging.String("fileKey", fileKey), logging.String("commentID", commentID), logging.String("emoji", emoji))

	err := lc.client.DeleteCommentReaction(ctx, fileKey, commentID, emoji)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("fileKey", fileKey))

	fields = append(fields, logging.String("commentID", commentID))

	fields = append(fields, logging.String("emoji", emoji))

	if err != nil {
		lc.logger.Error(ctx, "DeleteCommentReaction failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "DeleteCommentReaction success", fields...)
	}
	return err
}

// GetFileMetadata implements Client.GetFileMetadata with logging.
func (lc *LoggingClient) GetFileMetadata(ctx context.Context, fileKey string, opts ...GetFileMetadataOption) (*FileMeta, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "GetFileMetadata request", logging.String("fileKey", fileKey), logging.Any("opts", opts))

	result, err := lc.client.GetFileMetadata(ctx, fileKey, opts...)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("fileKey", fileKey))

	fields = append(fields, logging.Any("opts", opts))

	if err != nil {
		lc.logger.Error(ctx, "GetFileMetadata failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetFileMetadata success", fields...)
	}
	return result, err
}

// GetFileVersions implements Client.GetFileVersions with logging.
func (lc *LoggingClient) GetFileVersions(ctx context.Context, fileKey string, opts ...GetFileVersionsOption) ([]*Version, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "GetFileVersions request", logging.String("fileKey", fileKey), logging.Any("opts", opts))

	result, err := lc.client.GetFileVersions(ctx, fileKey, opts...)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("fileKey", fileKey))

	fields = append(fields, logging.Any("opts", opts))

	if err != nil {
		lc.logger.Error(ctx, "GetFileVersions failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetFileVersions success", fields...)
	}
	return result, err
}

// GetTeamStyles implements Client.GetTeamStyles with logging.
func (lc *LoggingClient) GetTeamStyles(ctx context.Context, teamID string) ([]*Style, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "GetTeamStyles request", logging.String("teamID", teamID))

	result, err := lc.client.GetTeamStyles(ctx, teamID)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("teamID", teamID))

	if err != nil {
		lc.logger.Error(ctx, "GetTeamStyles failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetTeamStyles success", fields...)
	}
	return result, err
}

// GetStyle implements Client.GetStyle with logging.
func (lc *LoggingClient) GetStyle(ctx context.Context, styleKey string) (*Style, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "GetStyle request", logging.String("styleKey", styleKey))

	result, err := lc.client.GetStyle(ctx, styleKey)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("styleKey", styleKey))

	if err != nil {
		lc.logger.Error(ctx, "GetStyle failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetStyle success", fields...)
	}
	return result, err
}

// GetFileStyles implements Client.GetFileStyles with logging.
func (lc *LoggingClient) GetFileStyles(ctx context.Context, fileKey string) ([]*Style, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "GetFileStyles request", logging.String("fileKey", fileKey))

	result, err := lc.client.GetFileStyles(ctx, fileKey)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("fileKey", fileKey))

	if err != nil {
		lc.logger.Error(ctx, "GetFileStyles failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetFileStyles success", fields...)
	}
	return result, err
}

// GetTeamComponents implements Client.GetTeamComponents with logging.
func (lc *LoggingClient) GetTeamComponents(ctx context.Context, teamID string) ([]*Component, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "GetTeamComponents request", logging.String("teamID", teamID))

	result, err := lc.client.GetTeamComponents(ctx, teamID)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("teamID", teamID))

	if err != nil {
		lc.logger.Error(ctx, "GetTeamComponents failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetTeamComponents success", fields...)
	}
	return result, err
}

// GetComponent implements Client.GetComponent with logging.
func (lc *LoggingClient) GetComponent(ctx context.Context, componentKey string) (*Component, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "GetComponent request", logging.String("componentKey", componentKey))

	result, err := lc.client.GetComponent(ctx, componentKey)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("componentKey", componentKey))

	if err != nil {
		lc.logger.Error(ctx, "GetComponent failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetComponent success", fields...)
	}
	return result, err
}

// GetTeamComponentSets implements Client.GetTeamComponentSets with logging.
func (lc *LoggingClient) GetTeamComponentSets(ctx context.Context, teamID string) ([]*ComponentSet, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "GetTeamComponentSets request", logging.String("teamID", teamID))

	result, err := lc.client.GetTeamComponentSets(ctx, teamID)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("teamID", teamID))

	if err != nil {
		lc.logger.Error(ctx, "GetTeamComponentSets failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetTeamComponentSets success", fields...)
	}
	return result, err
}

// GetComponentSet implements Client.GetComponentSet with logging.
func (lc *LoggingClient) GetComponentSet(ctx context.Context, componentSetKey string) (*ComponentSet, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "GetComponentSet request", logging.String("componentSetKey", componentSetKey))

	result, err := lc.client.GetComponentSet(ctx, componentSetKey)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("componentSetKey", componentSetKey))

	if err != nil {
		lc.logger.Error(ctx, "GetComponentSet failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetComponentSet success", fields...)
	}
	return result, err
}

// GetFileComponents implements Client.GetFileComponents with logging.
func (lc *LoggingClient) GetFileComponents(ctx context.Context, fileKey string) ([]*Component, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "GetFileComponents request", logging.String("fileKey", fileKey))

	result, err := lc.client.GetFileComponents(ctx, fileKey)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("fileKey", fileKey))

	if err != nil {
		lc.logger.Error(ctx, "GetFileComponents failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetFileComponents success", fields...)
	}
	return result, err
}

// GetTeamProjects implements Client.GetTeamProjects with logging.
func (lc *LoggingClient) GetTeamProjects(ctx context.Context, teamID string) ([]*Project, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "GetTeamProjects request", logging.String("teamID", teamID))

	result, err := lc.client.GetTeamProjects(ctx, teamID)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("teamID", teamID))

	if err != nil {
		lc.logger.Error(ctx, "GetTeamProjects failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetTeamProjects success", fields...)
	}
	return result, err
}

// GetProjectFiles implements Client.GetProjectFiles with logging.
func (lc *LoggingClient) GetProjectFiles(ctx context.Context, projectID string) ([]*File, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "GetProjectFiles request", logging.String("projectID", projectID))

	result, err := lc.client.GetProjectFiles(ctx, projectID)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("projectID", projectID))

	if err != nil {
		lc.logger.Error(ctx, "GetProjectFiles failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetProjectFiles success", fields...)
	}
	return result, err
}

// GetMe implements Client.GetMe with logging.
func (lc *LoggingClient) GetMe(ctx context.Context) (*User, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "GetMe request")

	result, err := lc.client.GetMe(ctx)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	if err != nil {
		lc.logger.Error(ctx, "GetMe failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetMe success", fields...)
	}
	return result, err
}

// GetFileVariables implements Client.GetFileVariables with logging.
func (lc *LoggingClient) GetFileVariables(ctx context.Context, fileKey string) ([]*Variable, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "GetFileVariables request", logging.String("fileKey", fileKey))

	result, err := lc.client.GetFileVariables(ctx, fileKey)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("fileKey", fileKey))

	if err != nil {
		lc.logger.Error(ctx, "GetFileVariables failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetFileVariables success", fields...)
	}
	return result, err
}

// GetTeamPublishedVariables implements Client.GetTeamPublishedVariables with logging.
func (lc *LoggingClient) GetTeamPublishedVariables(ctx context.Context, teamID string) ([]*Variable, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "GetTeamPublishedVariables request", logging.String("teamID", teamID))

	result, err := lc.client.GetTeamPublishedVariables(ctx, teamID)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("teamID", teamID))

	if err != nil {
		lc.logger.Error(ctx, "GetTeamPublishedVariables failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetTeamPublishedVariables success", fields...)
	}
	return result, err
}

// PostFileVariables implements Client.PostFileVariables with logging.
func (lc *LoggingClient) PostFileVariables(ctx context.Context, fileKey string, variables []*Variable) error {
	start := time.Now()
	lc.logger.Debug(ctx, "PostFileVariables request", logging.String("fileKey", fileKey), logging.Any("variables", variables))

	err := lc.client.PostFileVariables(ctx, fileKey, variables)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("fileKey", fileKey))

	fields = append(fields, logging.Any("variables", variables))

	if err != nil {
		lc.logger.Error(ctx, "PostFileVariables failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "PostFileVariables success", fields...)
	}
	return err
}

// GetFileDevResources implements Client.GetFileDevResources with logging.
func (lc *LoggingClient) GetFileDevResources(ctx context.Context, fileKey string) ([]*DevResource, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "GetFileDevResources request", logging.String("fileKey", fileKey))

	result, err := lc.client.GetFileDevResources(ctx, fileKey)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("fileKey", fileKey))

	if err != nil {
		lc.logger.Error(ctx, "GetFileDevResources failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetFileDevResources success", fields...)
	}
	return result, err
}

// PostDevResources implements Client.PostDevResources with logging.
func (lc *LoggingClient) PostDevResources(ctx context.Context, resources []*DevResource) error {
	start := time.Now()
	lc.logger.Debug(ctx, "PostDevResources request", logging.Any("resources", resources))

	err := lc.client.PostDevResources(ctx, resources)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.Any("resources", resources))

	if err != nil {
		lc.logger.Error(ctx, "PostDevResources failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "PostDevResources success", fields...)
	}
	return err
}

// PatchDevResources implements Client.PatchDevResources with logging.
func (lc *LoggingClient) PatchDevResources(ctx context.Context, resources []*DevResource) error {
	start := time.Now()
	lc.logger.Debug(ctx, "PatchDevResources request", logging.Any("resources", resources))

	err := lc.client.PatchDevResources(ctx, resources)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.Any("resources", resources))

	if err != nil {
		lc.logger.Error(ctx, "PatchDevResources failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "PatchDevResources success", fields...)
	}
	return err
}

// GetWebhooks implements Client.GetWebhooks with logging.
func (lc *LoggingClient) GetWebhooks(ctx context.Context) ([]*Webhook, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "GetWebhooks request")

	result, err := lc.client.GetWebhooks(ctx)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	if err != nil {
		lc.logger.Error(ctx, "GetWebhooks failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "GetWebhooks success", fields...)
	}
	return result, err
}

// CreateWebhook implements Client.CreateWebhook with logging.
func (lc *LoggingClient) CreateWebhook(ctx context.Context, webhook *WebhookRequest) (*Webhook, error) {
	start := time.Now()
	lc.logger.Debug(ctx, "CreateWebhook request", logging.Any("webhook", webhook))

	result, err := lc.client.CreateWebhook(ctx, webhook)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.Any("webhook", webhook))

	if err != nil {
		lc.logger.Error(ctx, "CreateWebhook failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "CreateWebhook success", fields...)
	}
	return result, err
}

// DeleteWebhook implements Client.DeleteWebhook with logging.
func (lc *LoggingClient) DeleteWebhook(ctx context.Context, webhookID string) error {
	start := time.Now()
	lc.logger.Debug(ctx, "DeleteWebhook request", logging.String("webhookID", webhookID))

	err := lc.client.DeleteWebhook(ctx, webhookID)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("webhookID", webhookID))

	if err != nil {
		lc.logger.Error(ctx, "DeleteWebhook failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "DeleteWebhook success", fields...)
	}
	return err
}

// UpdateWebhook implements Client.UpdateWebhook with logging.
func (lc *LoggingClient) UpdateWebhook(ctx context.Context, webhookID string, updates *WebhookUpdate) error {
	start := time.Now()
	lc.logger.Debug(ctx, "UpdateWebhook request", logging.String("webhookID", webhookID), logging.Any("updates", updates))

	err := lc.client.UpdateWebhook(ctx, webhookID, updates)

	duration := time.Since(start)
	fields := []logging.Field{
		logging.Float64("duration_ms", duration.Seconds()*1000),
	}

	fields = append(fields, logging.String("webhookID", webhookID))

	fields = append(fields, logging.Any("updates", updates))

	if err != nil {
		lc.logger.Error(ctx, "UpdateWebhook failed", append(fields, logging.Err(err))...)
	} else {
		lc.logger.Debug(ctx, "UpdateWebhook success", fields...)
	}
	return err
}
